server:
  port: 8081
  max-http-header-size: 2MB
  tomcat.max-http-form-post-size: 50MB

spring:
  profiles:
    active: dev
  application:
    name: playlet-internal-server
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 800MB
      max-request-size: 800MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

dscoins:
  login:
    ipLimit:
      enable: false
    googleLimit:
      enable: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

# SpringDoc 配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
